### ISSUE TITLE
Klassen in Python

### ISSUE THREAD

**Issue by enaut** [Hideakiii/School-Tasks#3]
An verschiedenen Stellen schreibst du dasselbe mehrfach auf. Zum Beispiel hier:

https://github.com/Hideakiii/School-Tasks/blob/498c21b7e62f3b78f9b417bc525d8afe91795de9/Pygame_Avalonion_v3.py#L31-L37

Letztendlich sind das ja jeweils variablen für Spieler 1 und für Spieler 2... das könnte viel eleganter mit Klassen gelöst werden. Eine Beschreibung von Python-Klassen kannst du hier finden:

https://www.hdm-stuttgart.de/~maucher/Python/html/Klassen.html

Natürlich gibts auch auf Youtube entsprechendes:

https://www.youtube.com/watch?v=i_uBcInKs5U

Es wäre hier zum Beispiel zu empfehlen eine Spieler-Klasse anzulegen:

```python
class Spieler():
    img=0 # wird später geladen
    name="Eduard"
    dead=False
    exists=True
    died_at_time = None
```

Dann kann man alle Variablen in `p1` und `p2` zusammenfassen:

```python
p1 = Spieler()
p2 = Spieler()
```

Soll nun Spieler 2 sterben:

```python
p2.dead=True
```

Genauso kannst du die `things` zusammenfassen. Wenn du dann alle `things` in eine Liste steckst, kannst du zum Beispiel mit einem `for` alle (nacheinander)bewegen, statt nur ein einziges.

**Comment by Hideakiii** [comment]
Okay Vielen Dank ,Ich werde das nachher mal ausprobieren.

**Comment by enaut** [comment]
Achso – wir haben ja das Snake auch mit einer Spielerklasse ausgestattet vielleicht hilft das ja auch: https://github.com/enaut/snake/blob/54c0258d35611f5e95ac5f67ada19998a507bcef/snake.py

**Comment by enaut** [comment]
Ein kleines pong Spiel, das Klassen verwendet könnte vielleicht auch noch helfen:
https://www.pygame.org/project/787/1352

**Comment by Hideakiii** [comment]
Vielen Dank für die Hilfe ,schaue mir das an wenn ich wieder zuhause bin .


Franz Dietrich <notifications@github.com> schrieb am Di., 29. Mai 2018,
21:35:
